/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package login.scherm;

import javax.swing.AbstractListModel;

/**
 *
 * @author jugraj
 */
public class menuScherm extends javax.swing.JFrame {

    /** Creates new form menuScherm */
    public menuScherm() {
        initComponents();
        GiveQuest.defaultBehaviour(this);
        GiveQuest.setButtonLook(jButton1);
        welkomLabel.setText("Welkom " + session.email);
        session.account_id = 2;
        
        
        
        //jList1.setModel(test);
        
    }
    
    
    
   /* public AbstractListModel<String> getDonatie(){
        ArrayList<String>  x = new ArrayList<>();
        int product_id = 0;

        
        try{
            //setting url for db connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test_db","test","Jugraj123");
            
            //creating query
            Statement stm = con.createStatement();
            
            ResultSet myQr = stm.executeQuery("select product_id from Donatie where id = " + session.account_id);
            while(myQr.next()){
                product_id = myQr.getInt("product_id");
                
            }
            
            myQr = stm.executeQuery("select naam from Product where product_id = " + product_id);
            
            while(myQr.next()){
                x.add(myQr.getString("naam"));
                
            }
            
            //stm.executeUpdate("insert into Donatie " + "values (" + product_id + ", " + session.account_id + ")");
            stm.close();
        }
        catch(SQLException e){
            e.printStackTrace();
            
        }
        
    } */
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geschiedenisScherm = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        donatieScherm = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        zoekField = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        resultaatScherm = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        geschiedenisKnop = new javax.swing.JButton();
        doneerButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        welkomLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        geschiedenisScherm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        geschiedenisScherm.setMinimumSize(new java.awt.Dimension(250, 400));
        geschiedenisScherm.setResizable(false);
        geschiedenisScherm.setSize(new java.awt.Dimension(250, 400));
        geschiedenisScherm.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBounds(new java.awt.Rectangle(0, 23, 250, 400));
        jPanel2.setMaximumSize(new java.awt.Dimension(250, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 418));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Geschiedenis");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ball_kleiner.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -200, -1, -1));

        jScrollPane2.setViewportView(jList1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, 280));

        geschiedenisScherm.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 420));

        donatieScherm.setMinimumSize(new java.awt.Dimension(250, 400));
        donatieScherm.setSize(new java.awt.Dimension(250, 418));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 418));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Donatie");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 20, 250, -1));

        zoekField.setText("Zoek");
        zoekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoekFieldActionPerformed(evt);
            }
        });
        jPanel3.add(zoekField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, -1));

        jButton6.setText("Zelf product toevoegen");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, -1));

        javax.swing.GroupLayout donatieSchermLayout = new javax.swing.GroupLayout(donatieScherm.getContentPane());
        donatieScherm.getContentPane().setLayout(donatieSchermLayout);
        donatieSchermLayout.setHorizontalGroup(
            donatieSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatieSchermLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        donatieSchermLayout.setVerticalGroup(
            donatieSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        resultaatScherm.setBounds(new java.awt.Rectangle(0, 23, 250, 400));
        resultaatScherm.setMinimumSize(new java.awt.Dimension(250, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 250, 400));
        setMaximumSize(new java.awt.Dimension(250, 400));
        setMinimumSize(new java.awt.Dimension(250, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setBounds(new java.awt.Rectangle(0, 23, 250, 400));
        jPanel1.setMaximumSize(new java.awt.Dimension(250, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Instellingen");
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 90, 90));

        jButton2.setText("Rewards");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 90));

        geschiedenisKnop.setText("Geschiedenis");
        geschiedenisKnop.setBorder(null);
        geschiedenisKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geschiedenisKnopActionPerformed(evt);
            }
        });
        jPanel1.add(geschiedenisKnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 90));

        doneerButton.setText("Doneren");
        doneerButton.setBorder(null);
        doneerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 80));

        jButton5.setText("Gebruiker");
        jButton5.setBorder(null);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 90));

        welkomLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        welkomLabel.setForeground(new java.awt.Color(0, 0, 0));
        welkomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welkomLabel.setText("Welkom email");
        jPanel1.add(welkomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Punten: 0");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ball_kleiner.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 418));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneerButtonActionPerformed
        /*donatieScherm.setVisible(true);
        donatieScherm.setLocationRelativeTo(this);
        donatieScherm.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setVisible(false);*/
        new ToevoegScherm().setVisible(true);
        
    }//GEN-LAST:event_doneerButtonActionPerformed

    private void geschiedenisKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geschiedenisKnopActionPerformed
        geschiedenisScherm.setLocationRelativeTo(this);
        geschiedenisScherm.setVisible(true);
        geschiedenisScherm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_geschiedenisKnopActionPerformed

    private void zoekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoekFieldActionPerformed

    }//GEN-LAST:event_zoekFieldActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ToevoegScherm tv = new ToevoegScherm();
        tv.setVisible(true);
        GiveQuest.defaultBehaviour(tv);
        tv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuScherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog donatieScherm;
    private javax.swing.JButton doneerButton;
    private javax.swing.JButton geschiedenisKnop;
    private javax.swing.JDialog geschiedenisScherm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog resultaatScherm;
    private javax.swing.JLabel welkomLabel;
    private javax.swing.JTextField zoekField;
    // End of variables declaration//GEN-END:variables

}
